/*ejecutar pasando 2 argumentos: 1ºRuta donde esta la BD  2ºNombre de la BD*/
DECLARE @DBName NVARCHAR(50)
DECLARE @BackupPath NVARCHAR(100)

------PARAMETROS
SET @DBName = 'Prueba'
SET @BackupPath = '''C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\Backup\'
------



DECLARE @ALTER_TEMPLATE VARCHAR(100)
DECLARE @BACKUP_TEMPLATE VARCHAR(100)

SET @ALTER_TEMPLATE = 'ALTER DATABASE {DBNAME} SET SINGLE_USER WITH ROLLBACK IMMEDIATE'
SET @BACKUP_TEMPLATE = 'RESTORE DATABASE {DBNAME} FROM DISK = {DBBACKUP} WITH REPLACE'


DECLARE @SQL_SCRIPT VARCHAR(200)

DECLARE @Dateaux date = GETDATE()
DECLARE @Date NVARCHAR(25)
SET @Date = REPLACE(CONVERT(varchar(10), @Dateaux, 104), '.', '') --ddmmyyyy

--SELECT @Date

DECLARE @BackupFile NVARCHAR(150)
SET @BackupFile = @BackupPath + @DBName + @Date + '.bak''' ---->C:\...\MSSQL\Backup\PruebaBD.bak

--print @BackupFile;

SET @SQL_SCRIPT = REPLACE(@ALTER_TEMPLATE, '{DBNAME}', @DBName)
EXECUTE (@SQL_SCRIPT) --EQUAL TO --> ALTER DATABASE Prueba SET SINGLE_USER WITH ROLLBACK IMMEDIATE


SET @SQL_SCRIPT = REPLACE(REPLACE(@BACKUP_TEMPLATE, '{DBNAME}', @DBName),'{DBBACKUP}', @BackupFile)
EXECUTE (@SQL_SCRIPT) --EQUAL TO --> RESTORE DATABASE Prueba FROM DISK = C:\.... WITH REPLACE

--SELECT @SQL_SCRIPT

--RESTORE DATABASE Prueba FROM DISK = 'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\Backup\Prueba06112019.bak'-- WITH REPLACE
